apiVersion: v1
data:
    age.agekey: ENC[AES256_GCM,data:DafG0919SZaVe1yx9nZQt5K9bqBhKbWOUm9kU6HIMeB8RyuwhBDDNef5uh8BqFp6kdJrv6XwBWOarqOL8UIxwY/9a6Z6RG8DKwoQz/35VUsONB9AmNEC5ydjM3WyV5cGr3EZxMu0jJVHZqpl29fUJYZYJDuZ4GredZcoo6CFvHCnaOIhICa8KOHTuL7X0hE5tE2/O5L+W8nI2LQV3+Gv8ao7BvGyR2e/bUrb2c7/bv7sZTsPwvn0m16fy24iSmc2u5k0LV0HWlxXuccZRmTMRozy2T/aH4MJb2yuJUXwimUF2yjB0tqcZuDXFb2BlCO8ev9GM4yW9NHRJuvd,iv:HcZEdXUhl02TDwMZoTwF87cWN8MbvKTStuxc0K7/UDc=,tag:BfbdG6pnLt2EP6ytZfNPSw==,type:str]
kind: Secret
metadata:
    name: age-key-secret
    namespace: flux-system
sops:
    age:
        - recipient: age1xcgfns2kv95sxvmx03mrp89yuwcq95utphcma0j2uglt47xz9g5srzmncg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZldySXo4bDMxOXR1R0ky
            QXBvaHl0OUpXSDJ4SGYyZUJpeXFqY1daclU4Cm5Nd3ZsbEVJaUpWa0dlOE5EQ05i
            eXp0d0U2em9EQnNOaGczaWhXUE4xQTAKLS0tIFZnSDB0RHRQS3crZU1vbmZjbEpw
            SjV1N1BpVzZGZVl5WFhtdStsZ2ZDTDgK1F1etqwkAwfqT7jV6QivZxtX79sXIf8w
            chE/Eb/u09cNKkZ9Incl0bfSnivBFfPAAX57arL74cOKkYGvxoTvmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-30T12:26:47Z"
    mac: ENC[AES256_GCM,data:otc6I9lnEaH6iz3YJi7U2S3HGrPAV76UUla/edpSVtk29fA1N7xlpPdJbNX64kvOEFdq/t8dpArRMn98yLWgv2LvpMtn5RD6sxIyMQ3s2E6phVM3L37zixMDjOGUCLRqphE01YNyZqY+LtLcLPmzRNZQmEn/BP3LsrQO8u5YoI0=,iv:zFOL+x4YJt7LIWwI3ih/hNRRuPtZC3Lqx2daRDWhS1s=,tag:Los6bmhdi1XlaanbLisKCQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
