apiVersion: v1
data:
    age.agekey: ENC[AES256_GCM,data:CT/1cJuKWkE8e2iElw0C/GlUjRKOJ7Mk8IOAswjM08eLGEb7mzzMCRPSnw/Dm7NK+sueyB1JKrNNkACQe6GfbGNAuQGnhswvT7EnB8P9GEBDm9BekjmJ2dVj+vy6qoSvZX7M4s3lH8gB7ifvYxfyqkac+khxTjFAqNWIs1fGIqug20/SxvheaW4dHYjXd5Vcfd+4rCkW2CuYm1JiGP7BsGJMm9L1niyLO5dgrGa4UbWJ+v3cIzHMFXSDbcrev3ab+kY/Zwiu3aSj2cTT7N4M6309EV1nyG1hg/6CmcMks+eIkhYrKRHzY+vYuotqkWwcfEhpK1TOGXMsPpRK,iv:XsihH8pLTce9Szq8njcs5JJAkISOwZwp3368RwGmNVw=,tag:5aGtZxd4VVrh0kTgom0yrg==,type:str]
kind: Secret
metadata:
    name: age-key-secret
    namespace: flux-system
sops:
    age:
        - recipient: age1xcgfns2kv95sxvmx03mrp89yuwcq95utphcma0j2uglt47xz9g5srzmncg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbjJiWTNkZnM5VWN5RU8r
            RVZrV0d1SnVuMFdYb0lheUlpVEdOOXhoczA4CkNwL1hJamdubmJZTlpZY2FDTkI5
            bG1EWGpBQ3U3bCswN0VzQkRtSlZ4OVUKLS0tIGZYMEQxWGFrWGZjRFNWVzRiNUQ3
            S2NONm5NOUhWemJCOVl0Q1c1V2dqYm8KkMXtBe/FJmEPAgxniFgrNhPIcM53HyDI
            8418xoCytdoAwL0QndkJ7Io+MknWCcTwYSJ5Hxw15HA0NDpREc+O/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-30T12:43:02Z"
    mac: ENC[AES256_GCM,data:BZ842JnoHOeQdwgryQiNz+SXUnXNG/T5DqV+54/kh9j9i1HJ3+Q+c3n/y4sRslPaZxLEe1Dyqk5khiijeYNfnfLsSgTsjwqfWc379Al/GNkFNq58dBjF4bY7fT0ZAqMpsfCD1mJCwd+2PQ9jCi0KHoqig7oX8eiJpfRF8+A8a8U=,iv:/BouCtlkMJUyz03l7Ieh19HinqTFfgy0x0zHFGxW5Y0=,tag:BasMTszNE5sRcS4oVW9E4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
